spring:
  datasource:
    url: jdbc:mysql://localhost:8889/JetBlue?createDatabaseIfNotExist=true
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true       # Set to true to format SQL nicely in logs
        hbm2ddl.auto: update
        check_nullability: true
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  #    show-sql: true             # Enable basic SQL logging to console
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
    test-connection: true

logging:
  level:
    org:
      hibernate:
      #        SQL: DEBUG             # Logs the SQL statements
      #        type: TRACE            # Logs SQL parameter binding values (optional, very verbose)
      springframework:
        http:
          converter:
            json: DEBUG
        security: TRACE
      jetblue:
        jetblue:
          Service:
            Implementation:

server:
  port: ${LOCAL_HOST_PORT}

aws:
  b2:
    bucket-name: ${AWS_B2_BUCKET_NAME}
    endpoint: ${AWS_B2_ENDPOINT}
    region: ${AWS_B2_REGION}
    access-key: ${AWS_B2_ACCESS_KEY}
    secret-key: ${AWS_B2_SECRET_KEY}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

stripe:
  apiKey: ${STRIPE_API_KEY}
  secretKey: ${STRIPE_SECRET_KEY}


