spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JetBlue?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Change to validate, create-drop, etc., as needed
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Additional configurations (if needed)
logging:
  level:
    org.hibernate.SQL: DEBUG   # To log SQL queries