spring:
  datasource:
    url: jdbc:mysql://localhost:8889/JetBlue?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true       # Set to true to format SQL nicely in logs
        hbm2ddl.auto: update
        check_nullability: true
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
#    show-sql: true             # Enable basic SQL logging to console

logging:
  level:
    org:
      hibernate:
      #        SQL: DEBUG             # Logs the SQL statements
      #        type: TRACE            # Logs SQL parameter binding values (optional, very verbose)
      springframework:
        http:
          converter:
            json: DEBUG
        security: TRACE
      jetblue:
        jetblue:
          Service:
            Implementation:

server:
  port: 8081

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
