POST localhost:{{serverPort}}/setAirline
Content-Type: application/json

{
  "airlineName": "Aer Lingus UK",
  "airlineCode": "EUK",
  "airlineUrl": "https://www.aerlingus.com/html/en-IE/home.html",
  "airlineLogoLink": "https://mediacentre.aerlingus.com/contents/archives/459/108/images/thumb1200x628_width/aerlingus_459108618666105_thumb.png",
  "colFormation": 5,
  "rowFormation": 70
}

###
POST localhost:{{serverPort}}/setAirline
Content-Type: application/json

{
  "airlineName": "Royal air maroc",
  "airlineCode": "RAM",
  "airlineUrl": "https://www.royalairmaroc.com/fr-fr",
  "airlineLogoLink": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Logo_Royal_Air_Maroc.svg",
  "colFormation": 5,
  "rowFormation": 70
}

###
@airlineCode=RAM

GET localhost:8081/getAirline/{{airlineCode}}
Content-Type: application/json

###
#@airlineCode=RAM
PUT localhost:{{serverPort}}/updateAirline/{{airlineCode}}
Content-Type: application/json

{
  "airlineName": "MOROCCAN ROYAL AIR",
  "airlineCode": "RAM",
  "airlineUrl": "https://www.royalairmaroc.com/fr-fr",
  "airlineLogoLink": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Logo_Royal_Air_Maroc.svg"
}

###

DELETE localhost:{{serverPort}}/deleteAirline/{{airlineCode}}
Content-Type: application/json