POST localhost:{{serverPort}}/setFlightStatus
Content-Type: application/json

{
  "status" : "Revoked"
}

###
POST localhost:{{serverPort}}/setListFlightsStatus
Content-Type: application/json

[
  "On Time",
  "Delayed",
  "Canceled",
  "Revoked"
]

###
GET localhost:{{serverPort}}/getFlightStatus
Content-Type: application/json

###
@status=Revoked
GET localhost:{{serverPort}}/getFlightStatus/{{status}}
Content-Type: application/json